#!/usr/bin/env sh
# Regenerate the gitignored build INPUTS for /design-sync (run from anywhere).
# These are derived from apps/web/components/ui sources, so a fresh clone runs
# this (plus build-css.sh) before the converter. Single source of truth for the
# family list is FAMILIES below — keep it in sync with config.json componentSrcMap.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
WEB="apps/web"

# file-stem : primary export name (the carded component)
FAMILIES='alert-dialog:AlertDialog
badge:Badge
button:Button
card:Card
chart-widget:ChartWidget
codeblock:CodeBlock
copy-button:CopyButton
data-table:DataTable
dialog:Dialog
dropdown-menu:DropdownMenu
empty-state:EmptyState
input:Input
label:Label
page-header:PageHeader
progress:Progress
select:Select
separator:Separator
sheet:Sheet
skeleton:Skeleton
switch:Switch
table:Table
tabs:Tabs
textarea:Textarea
tooltip:Tooltip'

# 0. browser process shim — many deps (next/image, prop-types) read process.env
#    at module-eval; without this the IIFE throws "process is not defined".
cat > "$WEB/.ds-shim.ts" <<'TS'
// AUTO-GENERATED by .design-sync/gen-dts.sh — minimal browser process shim.
;(globalThis as unknown as { process?: { env: Record<string, string> } }).process ||= {
  env: { NODE_ENV: 'production' },
}
TS

# 1. runtime barrel — defines the window.VibesboardUI surface (all subparts via export *).
#    The shim import MUST be first so it evaluates before any dep's module body.
{
  echo "// AUTO-GENERATED by .design-sync/gen-dts.sh — curated runtime barrel."
  echo "import './.ds-shim'"
  echo "$FAMILIES" | while IFS=: read -r f _; do echo "export * from './components/ui/$f'"; done
} > "$WEB/.ds-entry.tsx"

# 2. focused tsconfig for declaration emit (resolves the app's @/ alias)
cat > "$WEB/.ds-dts.tsconfig.json" <<'JSON'
{
  "compilerOptions": {
    "target": "ES2020", "module": "ESNext", "moduleResolution": "Bundler",
    "jsx": "react-jsx", "declaration": true, "emitDeclarationOnly": true,
    "skipLibCheck": true, "strict": false, "noEmit": false, "noEmitOnError": false,
    "incremental": false, "composite": false, "baseUrl": ".",
    "paths": { "@/*": ["./*"] }, "outDir": "./types/.ds-dts", "rootDir": ".",
    "types": ["react", "react-dom"]
  },
  "include": ["components/ui/**/*.tsx", "components/ui/**/*.ts", "lib/hooks/**/*.ts"]
}
JSON

# 3. emit the .d.ts tree (workspace .ts-extension import errors are tolerated)
rm -rf "$WEB/types/.ds-dts"
( cd "$WEB" && ../../node_modules/.bin/tsc -p .ds-dts.tsconfig.json ) || true

# 4. type-only entry barrel — holds the carded component list at the 24 primaries
{
  echo "// AUTO-GENERATED by .design-sync/gen-dts.sh — type-only barrel (24 primaries)."
  echo "$FAMILIES" | while IFS=: read -r f n; do echo "export { $n } from './types/.ds-dts/components/ui/$f'"; done
} > "$WEB/index.d.ts"

echo "gen-dts: wrote .ds-entry.tsx + index.d.ts + types/.ds-dts ($(find "$WEB/types/.ds-dts" -name '*.d.ts' | wc -l | tr -d ' ') decls)"
