name: "GCP Auth via Workload Identity Federation"
description: "Authenticate to GCP using Workload Identity Federation (keyless)"

inputs:
  workload_identity_provider:
    description: "WIF provider resource name"
    required: true
  service_account:
    description: "GCP service account email"
    required: true

runs:
  using: "composite"
  steps:
    - id: auth
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
